---
# tasks file for nagios

- name: Upgrade system
  yum:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Nagios and dependencies
  yum:
    name: epel-release, nagios
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
