---
# ***************************************
#
# * Linux Configuration Playbooks
#
# ***************************************

# Prepare RHEL based Linux hosts
- hosts: localhost
  connection: local
  #user: google
  become: yes
  vars:
    with_proxy: false
    with_containers: false
    with_nginx: false
    theuser: "root"
  environment:
#    HTTP_PROXY: http://proxy.example.com:3128
#    https_proxy: http://proxy.example.com:3128
#    http_proxy: http://proxy.example.com:3128
#    HTTPS_PROXY: http://proxy.example.com:3128
  roles:
    - roles/swmanagement
    #- roles/containers
    - roles/nginx
    

