---
# tasks file for swmanagement

- name: Customize motd
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'issue', dest: '/etc/issue' }
    - { src: 'issue.net', dest: '/etc/issue.net' }
    - { src: 'motd', dest: '/etc/motd' }

- name: Process RPM based distros
  include_tasks: 
    file: rpmbased.yml
  when: ansible_facts['os_family'] == "RedHat"
