---

- name: Upgrade system
  yum:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Git, tcpdump, nc,curl, wget, epel-release, python-setuptools and vim (Red Hat | CentOS)
  yum:
    name: curl,wget,vim,epel-release,git,nmap-ncat,tcpdump,python-setuptools
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install Git, tcpdump, nc,curl, wget, epel-release, python-setuptools and vim (Fedora)
  yum:
    name: curl,wget,vim,epel-release,git,nmap-ncat,tcpdump,python-setuptools
    state: present
  when: ansible_distribution == "Fedora"
