---

- name: Upgrade system
  yum:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Install nc,curl, wget, epel-release, python-setuptools and vim (Red Hat | CentOS)
  yum:
    name: curl,wget,vim,epel-release,nmap-ncat
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

#- name: Install Neofetch
#  yum:
#    name: neofetch
#    state: present
#  when: ansible_distribution == "Fedora"

- name: Install  nc,curl, wget, python-setuptools and vim (Fedora)
  yum:
    name: neofetch,curl,wget,vim,nmap-ncat,neofetch,python-virtualenv
    state: present
  when: ansible_distribution == "Fedora"

- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing
