---
# tasks file for containers
- meta: end_play
  when: not with_containers

- name: Install Docker Python SDK
  pip:
    name: docker
    state: present

- name: Create Mountpoint for local-persist - Debian based
  file:
    path: /mnt/docker/volumes
    state: directory
  when: ansible_facts['os_family'] == "Debian"

- name: Create Mountpoint for local-persist - Red Hat type OS
  file:
    path: /mnt/podman/volumes
    state: directory
    mode: '1777'
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Docker.io in Debian/Ubuntu
  apt:
    name: docker.io
    state: present
    force_apt_get: True
  when: ansible_facts['os_family'] == "Debian"

- name: Install Podman and Buildah in Red Hat type OS
  yum:
    name: podman,buildah
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Set correct SELinux fcontext
  sefcontext:
    target: '/mnt/podman(/.*)?'
    setype: container_file_t
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Restore fcontext settings
  shell: restorecon -R -v /mnt/podman
  when: ansible_facts['os_family'] == "RedHat"
